<?
$PERM["admin"]["G2"]="D";
$PERM["admin"]["G3"]="D";
$PERM["admin"]["G4"]="D";
$PERM["admin"]["G5"]="D";
$PERM["admin"]["G6"]="D";
$PERM["admin"]["*"]="D";
$PERM["search"]["6"]="W";
$PERM["products"]["6"]="W";
$PERM["services"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>